import = ["/home/sajid/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "None"
dynamic_padding = true
# opacity = 0.95

[window.padding]
x = 10
y = 5
